version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=task_manager_app_db
    volumes:
      - ./data:/docker-entrypoint-initdb.d
